=== milen-vm/SoftUni-Homework/3-level/Database-Applications/XMLBasicConcepts/StudentsXMLDocument/StudentsSchema.xsd
<?xml version="1.0" encoding="utf-8"?>
<xs:schema attributeFormDefault="unqualified" elementFormDefault="qualified" 
           targetNamespace="urn:students" xmlns:xs="http://www.w3.org/2001/XMLSchema">
  <xs:element name="students">
    <xs:complexType>
      <xs:sequence>
        <xs:element maxOccurs="unbounded" name="student">
          <xs:complexType>
            <xs:sequence>
              <xs:element name="name" type="xs:string" />
              <xs:element name="gender">
                <xs:simpleType>
                  <xs:restriction base="xs:string">
                    <xs:enumeration value="Male"/>
                    <xs:enumeration value="Female"/>
                  </xs:restriction>
                </xs:simpleType>
              </xs:element>
              <xs:element name="birth-date" type="xs:date" />
              <xs:element minOccurs="0" name="phone-number" type="xs:string"/>
              <xs:element name="email" type="xs:string" />
              <xs:element name="university" type="xs:string" />
              <xs:element name="specialty" type="xs:string" />
              <xs:element name="faculty-number"  minOccurs="0">
                <xs:simpleType>
                  <xs:restriction base="xs:string">
                    <xs:pattern value="[0-9]{10}"/>
                  </xs:restriction>
                </xs:simpleType>
              </xs:element>
              <xs:element name="taken-exams">
                <xs:complexType>
                  <xs:sequence>
                    <xs:element maxOccurs="unbounded" name="exam">
                      <xs:complexType>
                        <xs:sequence>
                          <xs:element name="name" type="xs:string" />
                          <xs:element name="date" type="xs:dateTime" />
                          <xs:element name="grade">
                            <xs:simpleType>
                              <xs:restriction base="xs:decimal">
                                <xs:minInclusive value="3"/>
                                <xs:maxInclusive value="6"/>
                              </xs:restriction>
                            </xs:simpleType>
                          </xs:element>
                        </xs:sequence>
                      </xs:complexType>
                    </xs:element>
                  </xs:sequence>
                </xs:complexType>
              </xs:element>
              <xs:element name="endorsements" minOccurs="0" maxOccurs="unbounded">
                <xs:complexType>
                  <xs:sequence>
                    <xs:element name="author" type="xs:string" minOccurs="1" maxOccurs="1" />
                    <xs:element name="email" type="xs:string" minOccurs="1" maxOccurs="1" />
                    <xs:element name="date" type="xs:date" minOccurs="1" maxOccurs="1" />
                    <xs:element name="text" type="xs:string" minOccurs="1" maxOccurs="1" />
                  </xs:sequence>
                </xs:complexType>
              </xs:element>
            </xs:sequence>
          </xs:complexType>
        </xs:element>
      </xs:sequence>
    </xs:complexType>
  </xs:element>
</xs:schema>

=== milen-vm/SoftUni-Homework/3-level/Database-Applications/XMLBasicConcepts/StudentsXMLDocument/Students.xml
<?xml version="1.0" encoding="utf-8"?>

<students xmlns="urn:students"
          xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
          xsi:schemaLocation="urn:students file://./StudentsSchema.xsd">
	<student>
		<name>Maria Petrova</name>
		<gender>Female</gender>
		<birth-date>1988-03-20</birth-date>
		<phone-number>02-9569-235</phone-number>
		<email>maria@abv.bg</email>
		<university>SoftUni</university>
		<specialty>Web developer</specialty>
		<faculty-number>1234567890</faculty-number>
		<taken-exams>
			<exam>
				<name>JavaScript</name>
				<date>2015-03-02T13:55:06Z</date>
				<grade>6.00</grade>
			</exam>
			<exam>
				<name>HTML</name>
				<date>2015-01-10T13:55:06Z</date>
				<grade>6.00</grade>
			</exam>
			<exam>
				<name>PHP</name>
				<date>2014-12-15T13:55:06Z</date>
				<grade>6.00</grade>
			</exam>
		</taken-exams>
	</student>
	<student>
		<name>Ivan Ivanov</name>
		<gender>Male</gender>
		<birth-date>1985-06-15</birth-date>
		<email>ivan@abv.bg</email>
		<university>SoftUni</university>
		<specialty>Web developer</specialty>
		<faculty-number>0234567890</faculty-number>
		<taken-exams>
			<exam>
				<name>JavaScript</name>
				<date>2015-03-02T13:55:06Z</date>
				<grade>5.12</grade>
			</exam>
			<exam>
				<name>HTML</name>
				<date>2015-01-10T13:55:06Z</date>
				<grade>6.00</grade>
			</exam>
			<exam>
				<name>PHP</name>
				<date>2014-12-15T13:55:06Z</date>
				<grade>5.23</grade>
			</exam>
		</taken-exams>
	</student>
	<student>
		<name>Dimitar Dimitrov</name>
		<gender>Male</gender>
		<birth-date>1981-09-15</birth-date>
		<phone-number>02-9509-885</phone-number>
		<email>dimo@abv.bg</email>
		<university>SoftUni</university>
		<specialty>Web developer</specialty>
		<taken-exams>
			<exam>
				<name>JavaScript</name>
				<date>2015-03-02T13:55:06Z</date>
				<grade>5.06</grade>
			</exam>
			<exam>
				<name>HTML</name>
				<date>2015-01-10T13:55:06Z</date>
				<grade>5.78</grade>
			</exam>
			<exam>
				<name>PHP</name>
				<date>2014-12-15T13:55:06Z</date>
				<grade>5.03</grade>
			</exam>
		</taken-exams>
	</student>
</students>
